# Generated by Django 2.2.12 on 2021-04-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
